apiVersion: apps/v1
kind: Deployment
metadata:
  name: snacktime
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: snacktime-web
  replicas: {{ default 1 .Values.backend.replicaCount | int }}
  template:
    metadata:
      labels:
        app: snacktime-web
    spec:
      containers:
      - name: web
        image: "{{ .Values.web.image }}:{{ .Values.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "3333"
        - name: HOST
          value: "0.0.0.0"
        ports:
        - name: entrypoint 
          containerPort: 3333

---
apiVersion: v1
kind: Service
metadata:
  name: snacktime-web
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: 80
    targetPort: "entrypoint"
  selector:
    app: snacktime-web